### PR TITLE
Navbar & Login

### PR DESCRIPTION
**Pull request by Nicanor008**
- [x] Addition of login & apply in navbar
- [x] Login page design, connection to backend not yet done

Screenshot 2020-11-14 at 23 26 07

### CODE REVIEW

**Comment by Nicanor008** [comment]
https://deploy-preview-25--shoman.netlify.app/auth

**Comment by neymarjimoh** [comment]
Looks nice @Nicanor008 . Are we coming up with a logo or leave the shoman logo as is??

**Comment by Nicanor008** [comment]
> Looks nice @Nicanor008 . Are we coming up with a logo or leave the shoman logo as is??

Thanks, @neymarjimoh, we definitely coming up with a new one, the one in use is for other personal project, was just a placeholder. The logo issue is here https://github.com/Nicanor008/shoman-FE/issues/10

**Comment by neymarjimoh** [comment]
> > Looks nice @Nicanor008 . Are we coming up with a logo or leave the shoman logo as is??
> 
> Thanks, @neymarjimoh, we definitely coming up with a new one, the one in use is for other personal project, was just a placeholder. The logo issue is here #10

alright. You're welcome @Nicanor008 .

**Pull request merged**
